// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acpgpktowymatigrgwuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjcGdwa3Rvd3ltYXRpZ3Jnd3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjYyMTgsImV4cCI6MjA2MzYwMjIxOH0.8OJvrerZBF2GcWjcoZCfHVaxAIXJjsWdiljt550-KNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);